
export const tableOption = {
    dialogWidth: '80%',
    dialogHeight: '80%',
    expandLevel: 2,
    border: true,
    index: true,
    tree: true,
    indexLabel: '序号',
    stripe: true,
    menuAlign: 'center',
    editBtn: false,
    delBtn: false,
    align: 'center',
    addBtn: false,
    viewBtn: true,
    submitBtn:false,
    emptyBtn:false,
    menuWidth: '190',
    column: [
        {
            label: '图标',
            prop: 'icon',
            type: 'upload',
            formslot:true,
            span: 12,
        },
        {
            label: '模型名称',
            prop: 'name',
            span: 12,
        },
        {
            label: '上线时间',
            prop: 'createTime',
            span: 12,
        },
        {
            label: '评价星级',
            prop: 'stars',
            span: 12,
            type: 'rate',
        },
        {
            label: "模型标识",
            prop: "udId",
            span: 12,
        },
        {
            label: '类型',
            prop: 'type',
            type: 'select',
            dicUrl: '/admin/dict/type/model_type',
            dicMethod: 'get',
            dicQuery: {},
            search: "true",
            span: 12,
        },
        {
            label: '权限标识',
            prop: 'permission',
            span: 12,
        },
        {
            label: '打开方式',
            prop: 'openType',
            type: 'select',
            dicUrl: '/admin/dict/type/model_open_type',
            dicMethod: 'get',
            dicQuery: {},
            span: 12,

        },
        {
            label: '链接地址',
            prop: 'links',
            type: 'textarea',
            span: 24,
        },
        {
            label: '简要信息',
            prop: 'remark',
            type: 'textarea',
            span: 24,
        },
    ]
}

export const editOption = {
    dialogWidth: '80%',
    dialogHeight: '80%',
    expandLevel: 2,
    border: true,
    index: true,
    tree: true,
    indexLabel: '序号',
    stripe: true,
    menuAlign: 'center',
    editBtn: false,
    delBtn: false,
    align: 'center',
    addBtn: false,
    viewBtn: true,
    submitBtn:false,
    emptyBtn:false,
    menuWidth: '190',
    column: [
        {
            label: '图标',
            prop: 'icon',
            type: 'upload',
            formslot:true,
            span: 12,
        },
        {
            label: '模型名称',
            prop: 'name',
            span: 12,
        },
        {
            label: '上线时间',
            prop: 'createTime',
            span: 12,
        },
        {
            label: '评价星级',
            prop: 'stars',
            span: 12,
            type: 'rate',
        },
        {
            label: "模型标识",
            prop: "udId",
            span: 12,
        },
        {
            label: '类型',
            prop: 'type',
            type: 'select',
            dicUrl: '/admin/dict/type/model_type',
            dicMethod: 'get',
            dicQuery: {},
            search: "true",
            span: 12,
        },
        {
            label: '权限标识',
            prop: 'permission',
            span: 12,
        },
        {
            label: '打开方式',
            prop: 'openType',
            type: 'select',
            dicUrl: '/admin/dict/type/model_open_type',
            dicMethod: 'get',
            dicQuery: {},
            span: 12,

        },
        {
            label: '链接地址',
            prop: 'links',
            type: 'textarea',
            span: 24,
        },
        {
            label: '简要信息',
            prop: 'remark',
            type: 'textarea',
            span: 24,
        },
    ]
}